server:
  port: 80
spring:
  application:
    name: web
eureka:
  client:
    service-url:
      defaultZone: http://eureka-service1.registryservice:7000/eureka,http://eureka-service2.registryservice:7000/eureka,http://eureka-service3.registryservice:7000/eureka
  instance:
    instance-id: web-80
    prefer-ip-address: true
    health-check-url-path: /actuator/health