server:
  port: 80
spring:
  application:
    name: web
eureka:
  client:
    service-url:
      defaultZone: http://wmtxg-springcloud-eureka.cd:8001/eureka/
  instance:
    instance-id: web-80
    prefer-ip-address: true
    health-check-url-path: /actuator/health
