server:
  port: 7001

spring: 
  application:
    name: sys
        
eureka:
  client: #客户端注册进eureka服务列表内
    service-url: 
      defaultZone: http://wmtxg-springcloud-eureka.cd:8001/eureka/  
  instance:
    instance-id: sys
    prefer-ip-address: true     #访问路径可以显示IP地址 
